server:
  host: 127.0.0.1
  port: 8081
  wiretap: true

logging:
  level:
    ROOT: DEBUG
    org.springframework.*: INFO

app:
  timezone: UTC

springdoc:
  version: 'v1'
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html